version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5.1
    working_directory: ~/40-avocados
    environment:
      JEKYLL_ENV: production
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - checkout
      - restore_cache:
          key: 40-avocados
      - save_cache:
          key: 40-avocados
          paths:
            - "docs"
      - run:
          name: "Generate Things"
          command: |
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
            /bin/bash Miniconda3-latest-Linux-x86_64.sh -b 
            $HOME/miniconda3/bin/python -m pip install pyaml
            cd $HOME/40-avocados/docs
            $HOME/miniconda3/bin/python ../.circleci/generate.py ../things.yml $HOME/40-avocados/docs
      - run:
      - store_artifacts: 
          path: docs
          destination: 40-avocados

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
